# Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Create NFL Dataset

Note: Numpy's random module excludes the high end, for example random.randint(14, 17) only returns 14 15 and 16.

In [2]:
num_players     = 50
position        = ['Running Back' for _ in range(num_players)]
player_id       = random.sample(range(1, 1000), num_players)
rushing_yards   = np.random.normal(1200, 200, num_players).clip(600, 1800).round(0)
receiving_yards = np.random.normal(600, 150, num_players).clip(100, 1100).round(0)
games_played    = np.random.randint(14, 18, num_players)
touches         = np.random.normal(240, 40, num_players).clip(40, 340).round(0)
fumbles         = np.random.randint(0, 5, num_players)
nfl_df = pd.DataFrame(
    {
        'Position': position,
        'Player ID': player_id,
        'Rushing Yards': rushing_yards,
        'Receiving Yards': receiving_yards,
        'Games Played': games_played,
        'Touches': touches,
        'Fumbles': fumbles
    }
)

# Quick EDA

In [3]:
nfl_df.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,1237.0,705.0,15,229.0,3
1,Running Back,716,1250.0,642.0,15,231.0,4
2,Running Back,604,1074.0,603.0,14,231.0,4
3,Running Back,638,843.0,403.0,17,177.0,4
4,Running Back,457,1202.0,487.0,15,214.0,0

# Normalization (Min-Max Sclaing)
- Scales values to a fixed range, usually [0, 1]
- Best for: when you need bounded values, neural networks, KNN
- Sensitive to outliers

In [4]:
from sklearn.preprocessing import MinMaxScaler

norm_scaler = MinMaxScaler()

cols_to_scale = ['Rushing Yards', 'Receiving Yards', 'Games Played', 'Touches', 'Fumbles']

nfl_df_norm = nfl_df.copy()
nfl_df_norm[cols_to_scale] = norm_scaler.fit_transform(nfl_df_norm[cols_to_scale])

In [5]:
nfl_df_norm.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.595518,0.524485,0.333333,0.391061,0.75
1,Running Back,716,0.609392,0.443299,0.333333,0.402235,1.00
2,Running Back,604,0.421558,0.393041,0.000000,0.402235,1.00
3,Running Back,638,0.175027,0.135309,1.000000,0.100559,1.00
4,Running Back,457,0.558164,0.243557,0.333333,0.307263,0.00

# Standardization (Z-Scaling)
- Centers data around mean=0 with std=1
- Best for: most ML algorithms, when data is normally distributed
- Less sensitive to outliers than MinMax

In [6]:
from sklearn.preprocessing import StandardScaler

stand_scaler = StandardScaler()

nfl_df_stand = nfl_df.copy()
nfl_df_stand[cols_to_scale] = stand_scaler.fit_transform(nfl_df_stand[cols_to_scale])

In [7]:
nfl_df_stand.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.305104,0.611369,-0.508349,-0.225065,0.574560
1,Running Back,716,0.364322,0.204479,-0.508349,-0.175272,1.242654
2,Running Back,604,-0.437386,-0.047406,-1.449737,-0.175272,1.242654
3,Running Back,638,-1.489628,-1.339122,1.374426,-1.519688,1.242654
4,Running Back,457,0.145674,-0.796601,-0.508349,-0.598514,-1.429720

Deciding which type of scaling we use depends on the application, but typicall Standardization is the better choice because it keeps the same distribution as the unscaled dataset.

# Robust Scaling (Mediam & IQR Scaling)
- Uses median and interquartile range (IQR) instead of mean/std
- Best for: data with significant outliers
- Most outlier-resistant of the common scalers

In [9]:
from sklearn.preprocessing import RobustScaler

robust_scaler = RobustScaler()

nfl_df_robust = nfl_df.copy()
nfl_df_robust[cols_to_scale] = robust_scaler.fit_transform(nfl_df_robust[cols_to_scale])

In [10]:
nfl_df_robust.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.343936,0.653979,0.000000,-0.132653,0.333333
1,Running Back,716,0.395626,0.217993,0.000000,-0.091837,0.666667
2,Running Back,604,-0.304175,-0.051903,-0.571429,-0.091837,0.666667
3,Running Back,638,-1.222664,-1.435986,1.142857,-1.193878,0.666667
4,Running Back,457,0.204771,-0.854671,0.000000,-0.438776,-0.666667

# Max Abs Scaling (Absolute Value Scaler)
- Scales by dividing by the maximum absolute value, range [-1, 1]
- Best for: sparse data, already centered at zero

In [13]:
from sklearn.preprocessing import MaxAbsScaler

abs_scaler = MaxAbsScaler()

nfl_df_abs = nfl_df.copy()

nfl_df_abs[cols_to_scale] = abs_scaler.fit_transform(nfl_df_abs[cols_to_scale])

In [14]:
nfl_df_abs.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.765470,0.656425,0.882353,0.677515,0.75
1,Running Back,716,0.773515,0.597765,0.882353,0.683432,1.00
2,Running Back,604,0.664604,0.561453,0.823529,0.683432,1.00
3,Running Back,638,0.521658,0.375233,1.000000,0.523669,1.00
4,Running Back,457,0.743812,0.453445,0.882353,0.633136,0.00

# Log Transformer (NumPy Log Scaling) 
- Reduces skewness in heavily skewed data
- Best for: right-skewed distributions, exponential data

In [15]:
nfl_df_log = nfl_df.copy()

nfl_df_log[cols_to_scale] = np.log1p(nfl_df_log[cols_to_scale])

In [16]:
nfl_df_log.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,7.121252,6.559615,2.772589,5.438079,1.386294
1,Running Back,716,7.131699,6.466145,2.772589,5.446737,1.609438
2,Running Back,604,6.980076,6.403574,2.708050,5.446737,1.609438
3,Running Back,638,6.738152,6.001415,2.890372,5.181784,1.609438
4,Running Back,457,7.092574,6.190315,2.772589,5.370638,0.000000

# Power Transformer
- Makes data more Gaussian-like
- Best for: when normality is required

In [20]:
nfl_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Player ID,50.0,514.22,273.932085,14.0,373.75,561.5,728.50,948.0
Rushing Yards,50.0,1170.02,221.760166,679.0,1051.75,1150.5,1303.25,1616.0
Receiving Yards,50.0,610.34,156.404709,298.0,535.00,610.5,679.50,1074.0
Games Played,50.0,15.54,1.073046,14.0,15.00,15.0,16.75,17.0
Touches,50.0,238.04,40.573923,159.0,213.25,235.5,262.25,338.0
Fumbles,50.0,2.14,1.511993,0.0,1.00,2.0,4.00,4.0

In [24]:
from sklearn.preprocessing import PowerTransformer

# Two methods
pt_yj = PowerTransformer(method='yeo-johnson')  # handles negative values

nfl_df_pt_yj = nfl_df.copy()

# Since our data has zeroes in the fumbles feature, we hae to use the yeo johnson method
nfl_df_pt_yj[cols_to_scale] = pt_yj.fit_transform(nfl_df_pt_yj[cols_to_scale])

In [25]:
nfl_df_pt_yj.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.288830,0.637163,-0.479575,-0.195925,0.615674
1,Running Back,716,0.349075,0.245255,-0.479575,-0.145663,1.191214
2,Running Back,604,-0.455271,-0.003859,-1.498740,-0.145663,1.191214
3,Running Back,638,-1.470233,-1.380562,1.344020,-1.563518,1.191214
4,Running Back,457,0.127273,-0.779382,-0.479575,-0.577980,-1.527130

In [ ]:
# Make a small shift of 1 for the Fumbles column to be able to use box-cox 
pt_bc = PowerTransformer(method='box-cox')

nfl_df_pt_bc = nfl_df.copy()
nfl_df_pt_bc['Fumbles'] = nfl_df_pt_bc['Fumbles'] + 1 # Shift 1 to get rid of zeroes

nfl_df_pt_bc[cols_to_scale] = pt_bc.fit_transform(nfl_df_pt_bc[cols_to_scale])

In [27]:
nfl_df_pt_bc.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.288836,0.637147,-0.479137,-0.195902,0.615674
1,Running Back,716,0.349081,0.245244,-0.479137,-0.145641,1.191214
2,Running Back,604,-0.455266,-0.003865,-1.499429,-0.145641,1.191214
3,Running Back,638,-1.470241,-1.380537,1.343606,-1.563542,1.191214
4,Running Back,457,0.127280,-0.779368,-0.479137,-0.577956,-1.527130

# Quantile Transformer (Uniform or Normal scaler)
- Maps data to a uniform or normal distribution
- Best for: non-linear scaling, when you want to force a specific distribution
- Most aggressive transformation

In [32]:
from sklearn.preprocessing import QuantileTransformer

# Uniform Scale
qt_uni = QuantileTransformer(output_distribution='uniform')

nfl_df_qt_uni = nfl_df.copy()
nfl_df_qt_uni[cols_to_scale] = qt_uni.fit_transform(nfl_df_qt_uni[cols_to_scale])

/Users/jackweyher/Desktop/Data Science/Data_Preprocessing/venv/lib/python3.14/site-packages/sklearn/preprocessing/_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (50). n_quantiles is set to n_samples.
  warnings.warn(

In [33]:
nfl_df_qt_uni.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.612245,0.836735,0.357143,0.397959,0.642857
1,Running Back,716,0.653061,0.612245,0.357143,0.438776,1.000000
2,Running Back,604,0.326531,0.469388,0.000000,0.438776,1.000000
3,Running Back,638,0.102041,0.081633,1.000000,0.071429,1.000000
4,Running Back,457,0.571429,0.163265,0.357143,0.265306,0.000000

In [34]:
qt_norm = QuantileTransformer(output_distribution='normal')

nfl_df_qt_norm = nfl_df.copy()
nfl_df_qt_norm[cols_to_scale] = qt_norm.fit_transform(nfl_df_qt_norm[cols_to_scale])

/Users/jackweyher/Desktop/Data Science/Data_Preprocessing/venv/lib/python3.14/site-packages/sklearn/preprocessing/_data.py:2885: UserWarning: n_quantiles (1000) is greater than the total number of samples (50). n_quantiles is set to n_samples.
  warnings.warn(

In [35]:
nfl_df_qt_norm.head()

,Position,Player ID,Rushing Yards,Receiving Yards,Games Played,Touches,Fumbles
0,Running Back,379,0.285175,0.981126,-0.366106,-0.258633,0.366106
1,Running Back,716,0.393598,0.285175,-0.366106,-0.154074,5.199338
2,Running Back,604,-0.449514,-0.076809,-5.199338,-0.154074,5.199338
3,Running Back,638,-1.270008,-1.394173,5.199338,-1.465234,5.199338
4,Running Back,457,0.180012,-0.981126,-0.366106,-0.627072,-5.199338