# Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Create NFL Dataset

Note: Numpy's random module excludes the high end, for example random.randint(14, 17) only returns 14 15 and 16.

In [14]:
num_players     = 50
position        = ['Running Back' for _ in range(num_players)]
player_id       = random.sample(range(1, 1000), num_players)
rushing_yards   = np.random.normal(1200, 200, num_players).clip(600, 1800).round(0)
receiving_yards = np.random.normal(600, 150, num_players).clip(100, 1100).round(0)
games_played    = np.random.randint(14, 18, num_players)
touches         = np.random.normal(240, 40, num_players).clip(40, 340).round(0)
fumbles         = np.random.randint(0, 5, num_players)
nfl_df = pd.DataFrame(
    {
        'Position': position,
        'Player ID': player_id,
        'Rushing Yards': rushing_yards,
        'Receiving Yards': receiving_yards,
        'Games Played': games_played,
        'Touches': touches,
        'Fumbles': fumbles
    }
)

In [15]:
nfl_data_norm = nfl_df.copy()
nfl_data_stand = nfl_df.copy()

# Quick EDA

In [16]:
nfl_df.head()

       Position  Player ID  Rushing Yards  ...  Games Played  Touches  Fumbles
0  Running Back        960         1426.0  ...            15    237.0        3
1  Running Back        786         1659.0  ...            14    299.0        2
2  Running Back        203         1181.0  ...            14    156.0        0
3  Running Back        935         1479.0  ...            16    217.0        4
4  Running Back        376         1330.0  ...            16    226.0        4

[5 rows x 7 columns]

# Normalization Sclaing

In [17]:
from sklearn.preprocessing import MinMaxScaler

norm_scaler = MinMaxScaler()

cols_to_scale = ['Rushing Yards', 'Receiving Yards', 'Games Played', 'Touches', 'Fumbles']

nfl_data_norm[cols_to_scale] = norm_scaler.fit_transform(nfl_data_norm[cols_to_scale])

In [18]:
nfl_data_norm.head()

       Position  Player ID  Rushing Yards  ...  Games Played   Touches  Fumbles
0  Running Back        960       0.729070  ...      0.333333  0.440217     0.75
1  Running Back        786       1.000000  ...      0.000000  0.777174     0.50
2  Running Back        203       0.444186  ...      0.000000  0.000000     0.00
3  Running Back        935       0.790698  ...      0.666667  0.331522     1.00
4  Running Back        376       0.617442  ...      0.666667  0.380435     1.00

[5 rows x 7 columns]

# Standardization Scaling

In [20]:
from sklearn.preprocessing import StandardScaler

stand_scaler = StandardScaler()

nfl_data_stand[cols_to_scale] = stand_scaler.fit_transform(nfl_data_stand[cols_to_scale])

In [21]:
nfl_data_stand.head()

       Position  Player ID  Rushing Yards  ...  Games Played   Touches   Fumbles
0  Running Back        960       1.201915  ...     -0.317221  0.002860  0.637480
1  Running Back        786       2.447894  ...     -1.308535  1.480599 -0.086929
2  Running Back        203      -0.108234  ...     -1.308535 -1.927734 -1.535748
3  Running Back        935       1.485335  ...      0.674094 -0.473830  1.361890
4  Running Back        376       0.688550  ...      0.674094 -0.259319  1.361890

[5 rows x 7 columns]

Deciding which type of scaling we use depends on the application, but typicall Standardization is the better choice because it keeps the same distribution as the unscaled dataset.